- name: Create docker data dir
  file: path={{ docker_data_dir }} owner=docker group=docker state=directory mode=0755

- name: Check if systemd exists
  stat: path=/usr/lib/systemd/system/
  register: systemd_check

- name: Docker systemd default config file
  template: src=docker-sysconfig.j2 dest=/etc/sysconfig/docker
  when: systemd_check.stat.exists == true
  
- name: Docker systemd file
  template: src=docker-service.j2 dest=/lib/systemd/system/docker.service backup=yes
  when: systemd_check.stat.exists == true
  notify:
    - Reload Systemd
    - Restart Docker

- name: Reload systemd
  shell: systemctl daemon-reload

- name: Make sure Docker is started
  service: name=docker.service state=restarted enabled=yes